name: Deploy Content to tal-euap-ws [e73add23-461d-46f8-bf6f-c6e191fd3f14]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-e73add23-461d-46f8-bf6f-c6e191fd3f14.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-e73add23-461d-46f8-bf6f-c6e191fd3f14.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'tal-test-rg'
      workspaceName: 'tal-euap-ws'
      workspaceId: 'b62db5e7-ba05-45d5-816c-9eec5c25d027'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: 'e73add23-461d-46f8-bf6f-c6e191fd3f14'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e73add23461d46f8bf6fc6e191fd3f14 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e73add23461d46f8bf6fc6e191fd3f14 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e73add23461d46f8bf6fc6e191fd3f14 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e73add23461d46f8bf6fc6e191fd3f14 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-e73add23-461d-46f8-bf6f-c6e191fd3f14.ps1